#!/usr/bin/env bash

set -Eeuo pipefail



SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
INFRA_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"

SHARED_TEMPLATE="${INFRA_DIR}/shared/main.bicep"
SHARED_PARAMETERS="${INFRA_DIR}/shared/parameters/shared.bicepparam"

OUTPUT_DIR="${INFRA_DIR}/.outputs"
OUTPUT_FILE="${OUTPUT_DIR}/shared.env"

SHARED_RESOURCE_GROUP="${SHARED_RESOURCE_GROUP:-realty-shared-rg}"
AZURE_LOCATION="${AZURE_LOCATION:-northeurope}"
AZURE_SUBSCRIPTION_ID="${AZURE_SUBSCRIPTION_ID:-}"

DEPLOYMENT_NAME="${SHARED_DEPLOYMENT_NAME:-realty-shared}"

log() {
  printf '\n[%s] %s\n' "$(date -u +'%Y-%m-%dT%H:%M:%SZ')" "$*"
}

fail() {
  printf '\nERROR: %s\n' "$*" >&2
  exit 1
}

write_shared_outputs_file() {
  local acr_id="$1"
  local acr_name="$2"
  local acr_login_server="$3"
  local temporary_file

  mkdir -p "$OUTPUT_DIR"

  temporary_file="$(mktemp "${OUTPUT_DIR}/shared.env.XXXXXX")"

  {
    printf '# Generated by deploy-shared.sh\n'
    printf '# Generated at %s\n' "$(date -u +'%Y-%m-%dT%H:%M:%SZ')"
    printf '# Do not edit manually.\n\n'

    printf 'export SHARED_RESOURCE_GROUP=%q\n' "$SHARED_RESOURCE_GROUP"
    printf 'export SHARED_DEPLOYMENT_NAME=%q\n' "$DEPLOYMENT_NAME"
    printf 'export ACR_ID=%q\n' "$acr_id"
    printf 'export ACR_NAME=%q\n' "$acr_name"
    printf 'export ACR_LOGIN_SERVER=%q\n' "$acr_login_server"
  } > "$temporary_file"

  chmod 600 "$temporary_file"
  mv "$temporary_file" "$OUTPUT_FILE"
}

require_command() {
  command -v "$1" >/dev/null 2>&1 ||
    fail "Required command '$1' is not installed."
}

require_file() {
  [[ -f "$1" ]] || fail "Required file not found: $1"
}

require_command az
require_file "$SHARED_TEMPLATE"
require_file "$SHARED_PARAMETERS"

log "Checking Azure authentication"

az account show >/dev/null 2>&1 ||
  fail "Not signed in to Azure. Run: az login"

if [[ -n "$AZURE_SUBSCRIPTION_ID" ]]; then
  log "Selecting Azure subscription: $AZURE_SUBSCRIPTION_ID"
  az account set --subscription "$AZURE_SUBSCRIPTION_ID"
fi

CURRENT_SUBSCRIPTION="$(
  az account show \
    --query "{name:name,id:id}" \
    --output json
)"

log "Using Azure subscription"
printf '%s\n' "$CURRENT_SUBSCRIPTION"

log "Ensuring shared resource group exists: $SHARED_RESOURCE_GROUP"

az group create \
  --name "$SHARED_RESOURCE_GROUP" \
  --location "$AZURE_LOCATION" \
  --tags \
    application=realty \
    scope=shared \
    managedBy=bicep \
  --output none

log "Compiling shared Bicep template"

az bicep build \
  --file "$SHARED_TEMPLATE" \
  --stdout \
  >/dev/null

log "Validating shared infrastructure"

az deployment group validate \
  --name "${DEPLOYMENT_NAME}-validate" \
  --resource-group "$SHARED_RESOURCE_GROUP" \
  --template-file "$SHARED_TEMPLATE" \
  --parameters "$SHARED_PARAMETERS" \
  --output none

log "Previewing shared infrastructure changes"

az deployment group what-if \
  --name "${DEPLOYMENT_NAME}-what-if" \
  --resource-group "$SHARED_RESOURCE_GROUP" \
  --template-file "$SHARED_TEMPLATE" \
  --parameters "$SHARED_PARAMETERS"

if [[ "${AUTO_APPROVE:-false}" != "true" ]]; then
  printf '\nDeploy these shared infrastructure changes? [y/N] '
  read -r answer

  case "$answer" in
    y | Y | yes | YES)
      ;;
    *)
      log "Deployment cancelled"
      exit 0
      ;;
  esac
fi

log "Deploying shared infrastructure"

az deployment group create \
  --name "$DEPLOYMENT_NAME" \
  --resource-group "$SHARED_RESOURCE_GROUP" \
  --template-file "$SHARED_TEMPLATE" \
  --parameters "$SHARED_PARAMETERS" \
  --output none

log "Reading shared deployment outputs"

ACR_ID="$(
  az deployment group show \
    --name "$DEPLOYMENT_NAME" \
    --resource-group "$SHARED_RESOURCE_GROUP" \
    --query "properties.outputs.acrId.value" \
    --output tsv
)"

ACR_NAME="$(
  az deployment group show \
    --name "$DEPLOYMENT_NAME" \
    --resource-group "$SHARED_RESOURCE_GROUP" \
    --query "properties.outputs.acrName.value" \
    --output tsv
)"

ACR_LOGIN_SERVER="$(
  az deployment group show \
    --name "$DEPLOYMENT_NAME" \
    --resource-group "$SHARED_RESOURCE_GROUP" \
    --query "properties.outputs.acrLoginServer.value" \
    --output tsv
)"

[[ -n "$ACR_ID" ]] ||

  fail "Shared deployment output 'acrId' was empty or missing."

[[ -n "$ACR_NAME" ]] ||

  fail "Shared deployment output 'acrName' was empty or missing."

[[ -n "$ACR_LOGIN_SERVER" ]] ||

    fail "Shared deployment output 'loginServer' was empty or missing."



log "Writing shared outputs to $OUTPUT_FILE"

write_shared_outputs_file \
  "$ACR_ID" \
  "$ACR_NAME" \
  "$ACR_LOGIN_SERVER"

log "Shared infrastructure deployment succeeded"

printf 'ACR name:         %s\n' "$ACR_NAME"
printf 'ACR login server: %s\n' "$ACR_LOGIN_SERVER"
printf 'Outputs file:     %s\n' "$OUTPUT_FILE"

printf '\nLoad these values into your current shell with:\n'
printf '  source %q\n' "$OUTPUT_FILE"
